# Nova seção

In [71]:
import pandas as pd

arquivo = "/content/ESCALA OPERACIONAL (RTS-BVT).xlsx"

df = pd.read_excel(
    arquivo,
    sheet_name="Valdebergue",
    header=12
)

df_bruto = pd.read_excel(
    arquivo,
    sheet_name="Valdebergue",
    header=None
)

In [72]:
datas = df_bruto.iloc[11, 11:]
dias = df.columns[11:]

for i in range(len(dias)):
    print(i, datas.iloc[i], "->", dias[i])

0 nan -> QUA
1 nan -> QUI
2 nan -> SEX
3 nan -> SÁB
4 nan -> DOM
5 nan -> SEG
6 nan -> TER
7 nan -> QUA.1
8 nan -> QUI.1
9 nan -> SEX.1
10 nan -> SÁB.1
11 nan -> DOM.1
12 nan -> SEG.1
13 nan -> TER.1
14 nan -> QUA.2
15 nan -> QUI.2
16 nan -> SEX.2
17 nan -> SÁB.2
18 nan -> DOM.2
19 nan -> SEG.2
20 nan -> TER.2
21 nan -> QUA.3
22 nan -> QUI.3
23 nan -> SEX.3
24 nan -> SÁB.3
25 nan -> DOM.3
26 nan -> SEG.3
27 nan -> TER.3
28 nan -> QUA.4
29 nan -> QUI.4
30 nan -> SEX.4
31 nan -> SÁB.4
32 nan -> DOM.4
33 nan -> SEG.4
34 nan -> TER.4
35 nan -> QUA.5
36 nan -> QUI.5
37 nan -> SEX.5
38 nan -> SÁB.5
39 nan -> DOM.5
40 nan -> SEG.5
41 nan -> TER.5
42 nan -> QUA.6
43 nan -> QUI.6
44 nan -> SEX.6
45 nan -> SÁB.6
46 nan -> DOM.6
47 2026-06-01 00:00:00 -> SEG.6
48 2026-06-02 00:00:00 -> TER.6
49 2026-06-03 00:00:00 -> QUA.7
50 2026-06-04 00:00:00 -> QUI.7
51 2026-06-05 00:00:00 -> SEX.7
52 2026-06-06 00:00:00 -> SÁB.7
53 2026-06-07 00:00:00 -> DOM.7
54 2026-06-08 00:00:00 -> SEG.7
55 2026-06-09 00:00:00 -> TER.7
56 2026-06-10 00:00:00 -> QUA.8
57 2026-06-11 00:00:00 -> QUI.8
58 2026-06-12 00:00:00 -> SEX.8
59 2026-06-13 00:00:00 -> SÁB.8
60 2026-06-14 00:00:00 -> DOM.8
61 2026-06-15 00:00:00 -> SEG.8
62 2026-06-16 00:00:00 -> TER.8
63 2026-06-17 00:00:00 -> QUA.9
64 2026-06-18 00:00:00 -> QUI.9
65 2026-06-19 00:00:00 -> SEX.9
66 2026-06-20 00:00:00 -> SÁB.9
67 2026-06-21 00:00:00 -> DOM.9
68 2026-06-22 00:00:00 -> SEG.9
69 2026-06-23 00:00:00 -> TER.9
70 2026-06-24 00:00:00 -> QUA.10
71 2026-06-25 00:00:00 -> QUI.10
72 2026-06-26 00:00:00 -> SEX.10
73 2026-06-27 00:00:00 -> SÁB.10
74 2026-06-28 00:00:00 -> DOM.10
75 2026-06-29 00:00:00 -> SEG.10
76 2026-06-30 00:00:00 -> TER.10
77 2026-07-01 00:00:00 -> Unnamed: 88
78 2026-07-02 00:00:00 -> Unnamed: 89
79 2026-07-03 00:00:00 -> Unnamed: 90
80 2026-07-04 00:00:00 -> Unnamed: 91
81 2026-07-05 00:00:00 -> Unnamed: 92
82 2026-07-06 00:00:00 -> Unnamed: 93
83 2026-07-07 00:00:00 -> Unnamed: 94
84 2026-07-08 00:00:00 -> Unnamed: 95
85 2026-07-09 00:00:00 -> Unnamed: 96
86 2026-07-10 00:00:00 -> Unnamed: 97
87 nan -> Unnamed: 98
88 nan -> Unnamed: 99
89 nan -> Unnamed: 100
90 nan -> Unnamed: 101
91 nan -> Unnamed: 102
92 nan -> Unnamed: 103
93 nan -> Unnamed: 104
94 nan -> Unnamed: 105
95 nan -> Unnamed: 106
96 nan -> Unnamed: 107
97 nan -> Unnamed: 108

In [73]:
def verificar_rede_por_data(indice_data):

    coluna = df.columns[11 + indice_data]

    resultado = df[
        (df["Op"] == "MVL") &
        (df[coluna] == "REDE")
    ]

    print("=" * 50)
    print(f"REDES PARA {datas.iloc[indice_data]}")
    print("=" * 50)

    for _, linha in resultado.iterrows():

        print(
            f"{linha['Cidade']} | "
            f"{linha['Turno']} | "
            f"{linha['Colaborador']}"
        )

    print(f"\nTotal: {len(resultado)}")

In [74]:
verificar_rede_por_data(1)

==================================================
REDES PARA nan
==================================================
Rio Claro | 1ºT | Ubirajara Fratucello
Simonsen | 1ºT | Elisangela Luque
Santa Fé | 1ºT | Roni Deivid

Total: 3

In [75]:
for i in range(11, 80):
    valor = df_bruto.iloc[11, i]

    if pd.notna(valor):
        print(i, valor)

58 2026-06-01 00:00:00
59 2026-06-02 00:00:00
60 2026-06-03 00:00:00
61 2026-06-04 00:00:00
62 2026-06-05 00:00:00
63 2026-06-06 00:00:00
64 2026-06-07 00:00:00
65 2026-06-08 00:00:00
66 2026-06-09 00:00:00
67 2026-06-10 00:00:00
68 2026-06-11 00:00:00
69 2026-06-12 00:00:00
70 2026-06-13 00:00:00
71 2026-06-14 00:00:00
72 2026-06-15 00:00:00
73 2026-06-16 00:00:00
74 2026-06-17 00:00:00
75 2026-06-18 00:00:00
76 2026-06-19 00:00:00
77 2026-06-20 00:00:00
78 2026-06-21 00:00:00
79 2026-06-22 00:00:00

In [76]:
print(len(df_bruto.iloc[11, 60:]))

49

In [77]:
print(df.columns[58])
print(df.columns[59])
print(df.columns[60])

SEG.6
TER.6
QUA.7

In [78]:
print(df_bruto.iloc[11,58])
print(df_bruto.iloc[11,59])
print(df_bruto.iloc[11,60])

2026-06-01 00:00:00
2026-06-02 00:00:00
2026-06-03 00:00:00

In [79]:
for i in range(58, 65):
    print(
        i,
        df_bruto.iloc[11, i],
        "|",
        df.columns[i]
    )

58 2026-06-01 00:00:00 | SEG.6
59 2026-06-02 00:00:00 | TER.6
60 2026-06-03 00:00:00 | QUA.7
61 2026-06-04 00:00:00 | QUI.7
62 2026-06-05 00:00:00 | SEX.7
63 2026-06-06 00:00:00 | SÁB.7
64 2026-06-07 00:00:00 | DOM.7

In [80]:
mapa_datas = {}

for i in range(58, 107):

    data = df_bruto.iloc[11, i]
    coluna = df.columns[i]

    mapa_datas[str(data.date())] = coluna

print(mapa_datas)

AttributeError: 'float' object has no attribute 'date'

In [81]:
print(mapa_datas["2026-06-15"])

SEG.8

In [82]:
def verificar_rede(data):

    coluna = mapa_datas[data]

    resultado = df[
        (df["Op"] == "MVL") &
        (df[coluna] == "REDE")
    ]

    print(f"\nREDES PARA {data}")
    print("=" * 50)

    for _, linha in resultado.iterrows():

        print(
            f"{linha['Cidade']} | "
            f"{linha['Turno']} | "
            f"{linha['Colaborador']}"
        )

    print(f"\nTotal: {len(resultado)}")

In [83]:
verificar_rede("2026-06-15")

REDES PARA 2026-06-15
==================================================
Santa Adélia | 1ºT |  Jamil Mattioli
Araraquara | 1ºT | Vaga aberta

Total: 2

In [84]:
def verificar_rede(data):

    coluna = mapa_datas[data]

    resultado = df[
        (df["Op"] == "MVL") &
        (df[coluna] == "REDE")
    ]

    print()
    print("=" * 60)
    print(f"COBERTURAS NECESSÁRIAS - {data}")
    print("=" * 60)

    for _, linha in resultado.iterrows():

        print(f"Cidade: {linha['Cidade']}")
        print(f"Turno : {linha['Turno']}")
        print(f"Nome  : {linha['Colaborador']}")
        print("-" * 40)

    print(f"\nTotal de redes: {len(resultado)}")

In [85]:
datas_disponiveis = list(mapa_datas.keys())

print(datas_disponiveis)

['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-04', '2026-06-05', '2026-06-06', '2026-06-07', '2026-06-08', '2026-06-09', '2026-06-10', '2026-06-11', '2026-06-12', '2026-06-13', '2026-06-14', '2026-06-15', '2026-06-16', '2026-06-17', '2026-06-18', '2026-06-19', '2026-06-20', '2026-06-21', '2026-06-22', '2026-06-23', '2026-06-24', '2026-06-25', '2026-06-26', '2026-06-27', '2026-06-28', '2026-06-29', '2026-06-30', '2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04', '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09', '2026-07-10']

In [87]:
def consultar_rede(data):

    coluna = mapa_datas[data]

    resultado = df[
        (df["Op"] == "MVL") &
        (df[coluna] == "REDE")
    ]

    return resultado[
        ["Cidade", "Turno", "Colaborador"]
    ]

In [89]:
consultar_rede("2026-06-15")

          Cidade Turno       Colaborador
4   Santa Adélia   1ºT   Jamil Mattioli
20    Araraquara   1ºT      Vaga aberta

In [90]:
def consultar_rede(data, operacao="MVL"):

    coluna = mapa_datas[data]

    resultado = df[
        (df["Op"] == operacao) &
        (df[coluna] == "REDE")
    ]

    return resultado[
        ["Cidade", "Turno", "Colaborador"]
    ]

In [91]:
consultar_rede("2026-06-15")

          Cidade Turno       Colaborador
4   Santa Adélia   1ºT   Jamil Mattioli
20    Araraquara   1ºT      Vaga aberta

In [92]:
consultar_rede("2026-06-15", "MVL")

          Cidade Turno       Colaborador
4   Santa Adélia   1ºT   Jamil Mattioli
20    Araraquara   1ºT      Vaga aberta

In [93]:
def total_redes(data, operacao="MVL"):

    return len(
        consultar_rede(data, operacao)
    )

In [94]:
total_redes("2026-06-15")

2

In [95]:
def cidades_com_rede(data):

    resultado = consultar_rede(data)

    return resultado["Cidade"].unique()

In [96]:
def cidades_com_rede(data):

    resultado = consultar_rede(data)

    return resultado["Cidade"].unique()

In [98]:
resumo = consultar_rede("2026-06-15")

print(f"Total de redes: {len(resumo)}")

resumo

Total de redes: 2

          Cidade Turno       Colaborador
4   Santa Adélia   1ºT   Jamil Mattioli
20    Araraquara   1ºT      Vaga aberta